import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "@/lib/api/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full border-b border-black/10 dark:border-white/10">
          <nav className="mx-auto max-w-5xl flex items-center gap-4 p-4 text-sm">
            <Link href="/" className="hover:underline">Home</Link>
            <Link href="/search" className="hover:underline">Search</Link>
            <Link href="/upload" className="hover:underline">Upload</Link>
            <Link href="/chat" className="hover:underline">Chat</Link>
          </nav>
        </header>
        <main className="mx-auto max-w-5xl p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
