const BRAIN_PLACEHOLDERS = [
    "🙂 Consulting the hippocampus",
    "🧩 Rewiring a few synapses",
    "🧮 Counting neurons (still a lot)",
    "📚 Indexing mental PDFs",
    "📟 Paging working memory",
    "📑 Cross-referencing footnotes in my head",
    "🧠 Spinning up the prefrontal cortex",
    "✏️ Sharpening imaginary pencils",
    "🤔 Goog... I mean, thinking really hard",
    "🏃‍♂️ Chasing a thought that just ran by",
    "🔭 Polishing cognitive lenses",
    "🏰 Defragmenting the memory palace",
    "🧬 Tickling the basal ganglia for hints",
    "⏳ Buffering stray ideas",
    "🎛️ Warming up the cerebellum",
    "🧶 Untangling a thought knot",
    "🗂️ Dusting off mental index cards",
    "✅ Running a quick sanity check",
    "🍊 Squeezing a bit more brain juice",
    "📐 Aligning mental vectors",
    "🧑‍🏫 Asking my inner librarian",
    "💻 Compiling neural code",
    "🔓 Decrypting a vague hunch",
    "🗃️ Sorting concepts by relevance",
    "🧲 Fetching semantic embeddings",
    "☕ Brewing a fresh insight",
    "🐑 Herding stray neurons",
    "🔮 Consulting the oracle of memory",
    "📥 Caching the gist",
    "🗺️ Mapping the idea space",
    "🔀 Rerouting around confusion",
    "🎚️ Calibrating intuition",
    "💧 Rehydrating context",
    "🔎 Zooming in on the crux",
    "🗜️ Zipping up stray thoughts",
    "📡 Pinging associative networks",
    "📏 Lining up evidence",
    "⚗️ Fusing facts with logic",
    "🧰 Refactoring the mental model",
    "🧐 Cross checking assumptions",
    "🎭 Peeking behind the abstraction curtain",
    "👉 Nudging attention back on track",
    "🪜 Filling in missing steps",
    "🗣️ Translating gut feeling into words",
    "✂️ Pruning irrelevant branches",
    "⬆️ Upgrading the working hypothesis",
    "🧊 Crunching the edge cases",
    "🔁 Double checking the premises",
    "🔄 Looping through possibilities",
    "📘 Finalizing the answer blueprint",
    "🧭 Navigating the maze of half-formed ideas",
    "⚙️ Synchronizing thought threads",
    "🪞 Reflecting on possible reflections",
    "📈 Extrapolating from fuzzy logic",
    "🌪️ Spinning up a thought storm",
    "🔧 Tightening loose associations",
    "🧤 Handling abstract concepts with care",
    "📊 Correlating intuition with evidence",
    "🌌 Staring into the mental void (it stares back)",
    "🧃 Distilling raw cognition into something drinkable",
    "🧱 Rebuilding a broken chain of reasoning",
    "🪶 Lightly dusting the theory shelves",
    "🧭 Charting the neural frontier",
    "🌿 Growing a hypothesis from scratch",
    "🪙 Flipping a mental coin of doubt",
    "🧯 Cooling off overheated ideas",
    "📎 Attaching context to the concept",
    "🧩 Snapping mental puzzle pieces together",
    "🎢 Riding the dopamine wave of discovery",
    "🧤 Putting on cognitive gloves",
    "🎩 Pulling insights out of the subconscious hat",
    "🎯 Zeroing in on the aha-moment",
    "📜 Reading between my own lines",
    "🪞 Mirroring internal dialogue",
    "📬 Checking the inbox of inspiration",
    "🎧 Listening for background thoughts",
    "🌉 Bridging gaps in logic",
    "🎨 Painting ideas with broad strokes",
    "🎬 Replaying mental footage frame by frame",
    "📌 Pinning down that slippery concept",
    "🧮 Balancing intuition and inference",
    "🚦 Waiting for clarity to turn green",
    "🧊 Cooling hot takes into reasoned ones",
    "🕰️ Rewinding recent thoughts for context",
    "🧹 Sweeping up cognitive residue",
    "🪄 Summoning the muse of coherence",
    "🔋 Charging up creative circuits",
    "🧤 Handling paradoxes carefully",
    "📻 Tuning in to the signal through the noise",
    "💫 Simulating multiple what-ifs",
    "🧭 Reorienting toward understanding",
    "🧼 Cleaning up stray metaphors",
    "🎈 Inflating a half-baked idea",
    "📠 Faxing intuition to logic",
    "🪜 Climbing abstraction levels",
    "🧠 Performing a recursive thought check",
    "🚪 Knocking on the door of insight",
    "🎲 Rolling mental dice for inspiration",
    "🪞 Aligning perception with perspective",
    "🌊 Surfing the brainwave continuum",
    "🧩 Finalizing the puzzle picture",
];

export function getRandomBrainPlaceholder(): string {
    const count = BRAIN_PLACEHOLDERS.length;
    if (count === 0) {
        return "Thinking it through";
    }
    const index = Math.floor(Math.random() * count);
    return BRAIN_PLACEHOLDERS[index];
}
