name: Enhance Release Notes

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  add-logo:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for release to be fully created
        run: sleep 5
        
      - name: Update Release with Logo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const logo = `<p align="center">
                <img src="https://raw.githubusercontent.com/${context.repo.owner}/${context.repo.repo}/main/frontend/public/Snappy/Snappy_light_readme.png" alt="Snappy" width="400"/>
              </p>
              
              ---
              
              `;
              
              console.log('Fetching release...');
              const release = await github.rest.repos.getRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: context.payload.release.id
              });
              
              console.log('Current release body:', release.data.body);
              
              // Check if logo already exists
              if (release.data.body && release.data.body.includes('Snappy_light_readme.png')) {
                console.log('Logo already present, skipping...');
                return;
              }
              
              const updatedBody = logo + (release.data.body || '');
              
              console.log('Updating release...');
              await github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: context.payload.release.id,
                body: updatedBody
              });
              
              console.log('✅ Added Snappy logo to release notes');
            } catch (error) {
              console.error('Error updating release:', error);
              throw error;
            }
